[package]
name = "referral_program"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-schema = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]
